.autodepend
BC5DIR=C:\BC5
VGAPDIR=C:\VGAP

###########################################################################

SRCS=auxdata.c pconfig.c crc.c enum.c hostio.c main.c portable.c \
	 vgapdata.c vgapmsg.c vgaputil.c worm.c doscvt.c rstmsg.c \
	 vgapdat1.c vgapdat2.c vgapdat3.c vgapdat4.c vgapdat5.c msgtmp.c \
     pgetopt.c points.c alldata.c vgapdat6.c vgapdat7.c vgapdat8.c vgapdat9.c \
     vgapdatb.c vgapdatc.c battle.c hullfunc.c listmat.c
OBJS=$(SRCS:.c=.obj)

CC=$(BC5DIR)\BIN\BCC32
INCDIR=$(BC5DIR)\include
LIBDIR=$(BC5DIR)\lib
TLIB=$(BC5DIR)\BIN\TLIB

all:    bcc32.cfg pdk32.lib ptscore sendmess crack killrace pmaster
lib:    bcc32.cfg pdk32.lib

bcc32.cfg:
	copy &&!
-w+ -w-sig -w-use -j3 -Z -d -O -Ob -Oe -Og -Oi -Om -Op -Ot -A
-UMICROSQUISH -N
-I.
-I$(INCDIR)
-L$(LIBDIR)
! bcc32.cfg

killrace: killrace.c phostpdk.h pdk32.lib
    $(CC) killrace.c pdk32.lib

sendmess: sendmess.c phostpdk.h pdk32.lib
    $(CC) sendmess.c pdk32.lib

crack: crack.c phostpdk.h pdk32.lib
    $(CC) crack.c pdk32.lib

ptscore: ptscore.c ptscore.h phostpdk.h pdk32.lib
    $(CC) ptscore.c pdk32.lib

pmaster: pmaster.c phostpdk.h pdk32.lib
    $(CC) pmaster.c pdk32.lib

pdk32.lib: $(OBJS)
     -@del pdk32.lib
     $(TLIB) pdk32.lib @&&!
+$(OBJS:.obj=.obj +)
!

install: pdk32.lib sendmess.exe killrace.exe crack.exe ptscore.exe pmaster.exe
     *copy /y sendmess.exe $(VGAPDIR)
     *copy /y killrace.exe $(VGAPDIR)
     *copy /y crack.exe    $(VGAPDIR)
     *copy /y ptscore.exe  $(VGAPDIR)
     *copy /y pmaster.exe  $(VGAPDIR)
     *copy /y pdk32.lib    $(VGAPDIR)

clean:
	 -@del *.obj
     -@del pdk32.lib
	 -@del *.exe
	 -@del *.log
	 -@del *.zip
	 -@del *.uue
     -@del bcc32.cfg
	 -@del defcfg.hi

realclean: clean

distrib:
        -@del pdk32.zip
        zip -9 pdk32.zip pdk32.lib phostpdk.h api.doc changes.doc \
			  install.doc legal.doc pdk.doc faq.doc ex*.c

putils: all
        -@del putils.zip
        zip -9 putils32.zip ptscore.exe sendmess.exe crack.exe killrace.exe \
                  pmaster.exe readme.doc ptscore.doc pmaster.cfg

archive:
      -@del pdk3.zip
      zip -9r -ll pdk3.zip *
