#
#  Makefile for tests, Unix version
#

CFLAGS = /I..
LDFLAGS = ..\pdk.lib

CDEP = ..\*.h
LDEP = ..\pdk.lib

TESTS = t_stand.exe

all: $(TESTS) t_sys.exe

clean:
	$(RM) *.obj
	$(RM) $(TESTS)

test: all
	for %i in ($(TESTS)) do %i || exit /b 1
	@echo "*** ok ***"




t_stand.exe: t_stand.obj $(LDEP)
	$(CC) /e$@ t_stand.obj $(LDFLAGS)

t_stand.obj: t_stand.c $(CDEP)


t_sys.exe: t_sys.obj $(LDEP)
	$(CC) /e$@ t_sys.obj $(LDFLAGS)

t_sys.obj: t_sys.c $(CDEP)

